version: "3"
services:
  hub:
    image: selenium/hub:4.0.0-rc-2-20210930
    container_name: SeleniumHub
    ports:
      - "4444:4444"
      - "4442:4442"
      - "4443:4443"
  chrome:
    image: selenium/node-chrome:4.0.0-rc-2-20210930
    shm_size: "2gb"
    ports:
      - "5900"
      - "7900"
    environment:
      - SE_EVENT_BUS_HOST=SeleniumHub
      - SE_EVENT_BUS_PUBLISH_PORT=4442
      - SE_EVENT_BUS_SUBSCRIBE_PORT=4443
      - SE_NODE_MAX_SESSIONS=5
    depends_on:
      - hub

  firefox:
    image: selenium/node-firefox:4.0.0-rc-2-20210930
    shm_size: "2gb"
    ports:
      - "5900"
      - "7900"
    environment:
      - SE_EVENT_BUS_HOST=SeleniumHub
      - SE_EVENT_BUS_PUBLISH_PORT=4442
      - SE_EVENT_BUS_SUBSCRIBE_PORT=4443
      - SE_NODE_MAX_SESSIONS=5
    depends_on:
      - hub

  edge:
    image: selenium/node-edge:4.0.0-rc-2-20210930
    shm_size: "2gb"
    ports:
      - "5900"
      - "7900"
    environment:
      - SE_EVENT_BUS_HOST=SeleniumHub
      - SE_EVENT_BUS_PUBLISH_PORT=4442
      - SE_EVENT_BUS_SUBSCRIBE_PORT=4443
      - SE_NODE_MAX_SESSIONS=5
    depends_on:
      - hub